# app-repo/.github/workflows/trigger_cd.yml
name: '1. Trigger CD Workflow (via GitHub App)'

on:
  push:
    branches:
      - main

jobs:
  trigger-cd-repo:
    runs-on: ubuntu-latest
    steps:
      # GitHub Appから認証トークンを生成
      - name: Generate GitHub App Token
        id: generate_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: 'MyOrgEntrance'
          repositories: 'cicd-test-ci-repo, cicd-test-cd-repo'

      # このトークンがアクセスできるリポジトリ一覧を出力
      - name: List accessible repositories
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          echo "--- Accessible repositories ---"
          gh api /installation/repositories | jq -r ".repositories[].full_name"
          echo "-------------------------------"

      # 適当な文字列をランダム生成
      - name: Generate random string
        id: random
        run: echo "random_id=$(date +%s)-$(openssl rand -hex 4)" >> $GITHUB_OUTPUT

      # metadata.yamlを作成
      - name: Create metadata.yaml
        run: |
          cat <<EOF > metadata.yaml
          ---
          - name: sample-app
            random: ${{ steps.random.outputs.random_id }}
            repository: ${{ github.repository }}
            commitid: ${{ github.sha }}
          EOF

      # metadata.yamlをアーティファクトとしてアップロード
      - name: Upload metadata as artifact
        id: upload_meta
        uses: actions/upload-artifact@v4
        with:
          name: metadata-artifact
          path: metadata.yaml

      # 生成したAppトークンを使ってcd-repoのワークフローを呼び出す
      - name: Trigger cd-repo workflow via GitHub CLI
        env:
          # ghコマンドの認証にAppトークンを使用する
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          # ペイロードを生成
          PAYLOAD=$(jq -n \
            --arg ci_repo "${{ github.repository }}" \
            --arg ci_run_id "${{ github.run_id }}" \
            --arg ci_art_metadata_name "metadata-artifact" \
            '{
              "event_type": "trigger-from-ci-repo",
              "client_payload": {
                "ci_repo": $ci_repo,
                "ci_run_id": $ci_run_id,
                "ci_metadata_art_id": $ci_metadata_art_id
              }
            }')
          echo "--- Generated Payload ---"
          echo "$PAYLOAD"
          echo "-------------------------"

          # cd-repoのワークフローの呼び出し
          echo "$PAYLOAD" | gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            /repos/MyOrgEntrance/cicd-test-cd-repo/dispatches \
            --input -
